### PR TITLE
Development/setting websockets

### PR DESCRIPTION
**Pull request by vaishakhanil**
# Setting up the websockets
- Installing channels package and updating the requirements.txt
- Setting up websockets

@Harishpsivan  Please include channels into documentation

@anjanaunnikrishnan, @RiomaxGit, @Harishpsivan  Please review my pull request

### CODE REVIEW

**Comment by RiomaxGit** [comment]
Need more details. @vaishakhanil 
Add documentation

**Review by anjanaunnikrishnan — APPROVED** [review]
Approved the setting of websockets.

**Review by harish-pangattil — COMMENTED** [review]
reviewed.

**Review by RiomaxGit — COMMENTED** [review]
Need more documentation. @vaishakhanil

**Pull request merged**
